import { useEffect, useState } from 'react';
import Forecast from './Forecast/Forecast/Forecast';
import SummaryChart from './SummaryChart/SummaryChart';
import axios from 'axios';

export default function Summary() {
  const [forecast, setForeCast] = useState([]);
  const [forcastDays, setForecastDays] = useState(5);
  const [forcastDay, setForecastDay] = useState([
    {
        "exactTime": "00:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716316200,
        "time": "2024-05-22 00:00",
        "temp_c": 30.1,
        "temp_f": 86.1,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 8.7,
        "wind_kph": 14,
        "wind_degree": 135,
        "wind_dir": "SE",
        "pressure_mb": 1004,
        "pressure_in": 29.63,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 77,
        "cloud": 22,
        "feelslike_c": 36.9,
        "feelslike_f": 98.3,
        "windchill_c": 30.1,
        "windchill_f": 86.1,
        "heatindex_c": 36.9,
        "heatindex_f": 98.3,
        "dewpoint_c": 25.7,
        "dewpoint_f": 78.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 12.4,
        "gust_kph": 19.9,
        "uv": 1,
        "air_quality": {
            "co": 260.4,
            "no2": 3,
            "o3": 18.2,
            "so2": 0.9,
            "pm2_5": 1.9,
            "pm10": 4.3,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "01:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716319800,
        "time": "2024-05-22 01:00",
        "temp_c": 30,
        "temp_f": 85.9,
        "is_day": 0,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 7.8,
        "wind_kph": 12.6,
        "wind_degree": 135,
        "wind_dir": "SE",
        "pressure_mb": 1003,
        "pressure_in": 29.62,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 78,
        "cloud": 30,
        "feelslike_c": 36.6,
        "feelslike_f": 97.9,
        "windchill_c": 30,
        "windchill_f": 85.9,
        "heatindex_c": 36.6,
        "heatindex_f": 97.9,
        "dewpoint_c": 25.7,
        "dewpoint_f": 78.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 11.1,
        "gust_kph": 17.9,
        "uv": 1,
        "air_quality": {
            "co": 277,
            "no2": 3.9,
            "o3": 15,
            "so2": 0.9,
            "pm2_5": 2.4,
            "pm10": 5.3,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "02:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716323400,
        "time": "2024-05-22 02:00",
        "temp_c": 29.7,
        "temp_f": 85.4,
        "is_day": 0,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 5.1,
        "wind_kph": 8.3,
        "wind_degree": 107,
        "wind_dir": "ESE",
        "pressure_mb": 1003,
        "pressure_in": 29.63,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 78,
        "cloud": 34,
        "feelslike_c": 36,
        "feelslike_f": 96.8,
        "windchill_c": 29.7,
        "windchill_f": 85.4,
        "heatindex_c": 36,
        "heatindex_f": 96.8,
        "dewpoint_c": 25.5,
        "dewpoint_f": 77.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 7.3,
        "gust_kph": 11.8,
        "uv": 1,
        "air_quality": {
            "co": 297.1,
            "no2": 4.8,
            "o3": 12,
            "so2": 1,
            "pm2_5": 3.2,
            "pm10": 6.7,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "03:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716327000,
        "time": "2024-05-22 03:00",
        "temp_c": 29.5,
        "temp_f": 85.1,
        "is_day": 0,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003
        },
        "wind_mph": 4.7,
        "wind_kph": 7.6,
        "wind_degree": 68,
        "wind_dir": "ENE",
        "pressure_mb": 1003,
        "pressure_in": 29.62,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 79,
        "cloud": 34,
        "feelslike_c": 35.8,
        "feelslike_f": 96.4,
        "windchill_c": 29.5,
        "windchill_f": 85.1,
        "heatindex_c": 35.8,
        "heatindex_f": 96.4,
        "dewpoint_c": 25.5,
        "dewpoint_f": 77.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 6.7,
        "gust_kph": 10.8,
        "uv": 1,
        "air_quality": {
            "co": 320.4,
            "no2": 6,
            "o3": 8.9,
            "so2": 1.3,
            "pm2_5": 4.2,
            "pm10": 8.7,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "04:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716330600,
        "time": "2024-05-22 04:00",
        "temp_c": 29.2,
        "temp_f": 84.6,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 5.8,
        "wind_kph": 9.4,
        "wind_degree": 63,
        "wind_dir": "ENE",
        "pressure_mb": 1003,
        "pressure_in": 29.62,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 81,
        "cloud": 22,
        "feelslike_c": 35.4,
        "feelslike_f": 95.6,
        "windchill_c": 29.2,
        "windchill_f": 84.6,
        "heatindex_c": 35.4,
        "heatindex_f": 95.6,
        "dewpoint_c": 25.6,
        "dewpoint_f": 78,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.5,
        "gust_kph": 13.6,
        "uv": 1,
        "air_quality": {
            "co": 343.8,
            "no2": 6.9,
            "o3": 6,
            "so2": 1.4,
            "pm2_5": 5.3,
            "pm10": 10.8,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "05:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716334200,
        "time": "2024-05-22 05:00",
        "temp_c": 29,
        "temp_f": 84.3,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 5.4,
        "wind_kph": 8.6,
        "wind_degree": 57,
        "wind_dir": "ENE",
        "pressure_mb": 1003,
        "pressure_in": 29.63,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 82,
        "cloud": 15,
        "feelslike_c": 35.2,
        "feelslike_f": 95.3,
        "windchill_c": 29,
        "windchill_f": 84.3,
        "heatindex_c": 35.2,
        "heatindex_f": 95.3,
        "dewpoint_c": 25.7,
        "dewpoint_f": 78.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 7.9,
        "gust_kph": 12.6,
        "uv": 1,
        "air_quality": {
            "co": 367.2,
            "no2": 7.5,
            "o3": 3.8,
            "so2": 1.4,
            "pm2_5": 6.2,
            "pm10": 12.7,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "06:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716337800,
        "time": "2024-05-22 06:00",
        "temp_c": 29.4,
        "temp_f": 84.9,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 4.9,
        "wind_kph": 7.9,
        "wind_degree": 54,
        "wind_dir": "NE",
        "pressure_mb": 1004,
        "pressure_in": 29.64,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 80,
        "cloud": 19,
        "feelslike_c": 35.6,
        "feelslike_f": 96.1,
        "windchill_c": 29.4,
        "windchill_f": 84.9,
        "heatindex_c": 35.6,
        "heatindex_f": 96.1,
        "dewpoint_c": 25.6,
        "dewpoint_f": 78,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 6.7,
        "gust_kph": 10.8,
        "uv": 7,
        "air_quality": {
            "co": 397.2,
            "no2": 7.5,
            "o3": 2.1,
            "so2": 1.5,
            "pm2_5": 7.6,
            "pm10": 15.3,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "07:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716341400,
        "time": "2024-05-22 07:00",
        "temp_c": 30.3,
        "temp_f": 86.6,
        "is_day": 1,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 5.6,
        "wind_kph": 9,
        "wind_degree": 62,
        "wind_dir": "ENE",
        "pressure_mb": 1004,
        "pressure_in": 29.66,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 74,
        "cloud": 32,
        "feelslike_c": 36.8,
        "feelslike_f": 98.2,
        "windchill_c": 30.3,
        "windchill_f": 86.6,
        "heatindex_c": 36.8,
        "heatindex_f": 98.2,
        "dewpoint_c": 25.3,
        "dewpoint_f": 77.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 7,
        "gust_kph": 11.3,
        "uv": 8,
        "air_quality": {
            "co": 454,
            "no2": 5,
            "o3": 4.2,
            "so2": 1.9,
            "pm2_5": 9.7,
            "pm10": 20.4,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "08:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716345000,
        "time": "2024-05-22 08:00",
        "temp_c": 31.4,
        "temp_f": 88.6,
        "is_day": 1,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 6.3,
        "wind_kph": 10.1,
        "wind_degree": 81,
        "wind_dir": "E",
        "pressure_mb": 1005,
        "pressure_in": 29.68,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 68,
        "cloud": 25,
        "feelslike_c": 37.9,
        "feelslike_f": 100.2,
        "windchill_c": 31.4,
        "windchill_f": 88.6,
        "heatindex_c": 37.9,
        "heatindex_f": 100.2,
        "dewpoint_c": 24.7,
        "dewpoint_f": 76.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 7.4,
        "gust_kph": 12,
        "uv": 8,
        "air_quality": {
            "co": 494,
            "no2": 5,
            "o3": 10.5,
            "so2": 2.2,
            "pm2_5": 11.5,
            "pm10": 24.1,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "09:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716348600,
        "time": "2024-05-22 09:00",
        "temp_c": 32.6,
        "temp_f": 90.6,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 7.4,
        "wind_kph": 11.9,
        "wind_degree": 102,
        "wind_dir": "ESE",
        "pressure_mb": 1005,
        "pressure_in": 29.68,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 62,
        "cloud": 15,
        "feelslike_c": 39.2,
        "feelslike_f": 102.5,
        "windchill_c": 32.6,
        "windchill_f": 90.6,
        "heatindex_c": 39.2,
        "heatindex_f": 102.5,
        "dewpoint_c": 24.3,
        "dewpoint_f": 75.8,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.5,
        "gust_kph": 13.7,
        "uv": 8,
        "air_quality": {
            "co": 273.7,
            "no2": 2.1,
            "o3": 34.7,
            "so2": 1,
            "pm2_5": 3.9,
            "pm10": 7.7,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "10:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716352200,
        "time": "2024-05-22 10:00",
        "temp_c": 33.6,
        "temp_f": 92.5,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 7.4,
        "wind_kph": 11.9,
        "wind_degree": 119,
        "wind_dir": "ESE",
        "pressure_mb": 1005,
        "pressure_in": 29.67,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 58,
        "cloud": 11,
        "feelslike_c": 40.4,
        "feelslike_f": 104.8,
        "windchill_c": 33.6,
        "windchill_f": 92.5,
        "heatindex_c": 40.4,
        "heatindex_f": 104.8,
        "dewpoint_c": 24.1,
        "dewpoint_f": 75.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.5,
        "gust_kph": 13.7,
        "uv": 8,
        "air_quality": {
            "co": 257,
            "no2": 1.6,
            "o3": 43.3,
            "so2": 1.1,
            "pm2_5": 4.2,
            "pm10": 6.9,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "11:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716355800,
        "time": "2024-05-22 11:00",
        "temp_c": 34.5,
        "temp_f": 94,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 8.1,
        "wind_kph": 13,
        "wind_degree": 128,
        "wind_dir": "SE",
        "pressure_mb": 1004,
        "pressure_in": 29.64,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 54,
        "cloud": 14,
        "feelslike_c": 41.5,
        "feelslike_f": 106.6,
        "windchill_c": 34.5,
        "windchill_f": 94,
        "heatindex_c": 41.5,
        "heatindex_f": 106.6,
        "dewpoint_c": 24,
        "dewpoint_f": 75.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 9.3,
        "gust_kph": 14.9,
        "uv": 8,
        "air_quality": {
            "co": 260.4,
            "no2": 1.8,
            "o3": 48.6,
            "so2": 1.3,
            "pm2_5": 5.4,
            "pm10": 7.8,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "12:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716359400,
        "time": "2024-05-22 12:00",
        "temp_c": 35,
        "temp_f": 95,
        "is_day": 1,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 10.5,
        "wind_kph": 16.9,
        "wind_degree": 132,
        "wind_dir": "SE",
        "pressure_mb": 1003,
        "pressure_in": 29.61,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 53,
        "cloud": 27,
        "feelslike_c": 42.5,
        "feelslike_f": 108.4,
        "windchill_c": 35,
        "windchill_f": 95,
        "heatindex_c": 42.5,
        "heatindex_f": 108.4,
        "dewpoint_c": 24.1,
        "dewpoint_f": 75.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 12.1,
        "gust_kph": 19.5,
        "uv": 9,
        "air_quality": {
            "co": 263.7,
            "no2": 2,
            "o3": 53.6,
            "so2": 1.6,
            "pm2_5": 7.1,
            "pm10": 9.3,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "13:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716363000,
        "time": "2024-05-22 13:00",
        "temp_c": 35,
        "temp_f": 94.9,
        "is_day": 1,
        "condition": {
            "text": "Partly Cloudy ",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 12.8,
        "wind_kph": 20.5,
        "wind_degree": 134,
        "wind_dir": "SE",
        "pressure_mb": 1002,
        "pressure_in": 29.58,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 54,
        "cloud": 31,
        "feelslike_c": 42.4,
        "feelslike_f": 108.3,
        "windchill_c": 35,
        "windchill_f": 94.9,
        "heatindex_c": 42.4,
        "heatindex_f": 108.3,
        "dewpoint_c": 24.1,
        "dewpoint_f": 75.4,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 14.7,
        "gust_kph": 23.6,
        "uv": 8,
        "air_quality": {
            "co": 263.7,
            "no2": 2.5,
            "o3": 53.6,
            "so2": 2,
            "pm2_5": 9,
            "pm10": 11.1,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "14:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716366600,
        "time": "2024-05-22 14:00",
        "temp_c": 34.6,
        "temp_f": 94.2,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 14.1,
        "wind_kph": 22.7,
        "wind_degree": 143,
        "wind_dir": "SE",
        "pressure_mb": 1001,
        "pressure_in": 29.55,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 55,
        "cloud": 22,
        "feelslike_c": 41.9,
        "feelslike_f": 107.4,
        "windchill_c": 34.6,
        "windchill_f": 94.2,
        "heatindex_c": 41.9,
        "heatindex_f": 107.4,
        "dewpoint_c": 24.2,
        "dewpoint_f": 75.5,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 16.2,
        "gust_kph": 26.1,
        "uv": 8,
        "air_quality": {
            "co": 257,
            "no2": 4.2,
            "o3": 47.9,
            "so2": 3.6,
            "pm2_5": 11.3,
            "pm10": 13.5,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "15:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716370200,
        "time": "2024-05-22 15:00",
        "temp_c": 33.9,
        "temp_f": 93,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 14.5,
        "wind_kph": 23.4,
        "wind_degree": 152,
        "wind_dir": "SSE",
        "pressure_mb": 1000,
        "pressure_in": 29.54,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 58,
        "cloud": 22,
        "feelslike_c": 41.1,
        "feelslike_f": 106.1,
        "windchill_c": 33.9,
        "windchill_f": 93,
        "heatindex_c": 41.1,
        "heatindex_f": 106.1,
        "dewpoint_c": 24.4,
        "dewpoint_f": 75.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 16.7,
        "gust_kph": 26.9,
        "uv": 8,
        "air_quality": {
            "co": 250.3,
            "no2": 4.8,
            "o3": 41.1,
            "so2": 5.3,
            "pm2_5": 10.4,
            "pm10": 12.5,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "16:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716373800,
        "time": "2024-05-22 16:00",
        "temp_c": 37,
        "temp_f": 98.6,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 9.4,
        "wind_kph": 15.1,
        "wind_degree": 100,
        "wind_dir": "E",
        "pressure_mb": 999,
        "pressure_in": 29.5,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 48,
        "cloud": 50,
        "feelslike_c": 39.7,
        "feelslike_f": 103.5,
        "windchill_c": 32.9,
        "windchill_f": 91.3,
        "heatindex_c": 39.7,
        "heatindex_f": 103.5,
        "dewpoint_c": 24.4,
        "dewpoint_f": 75.9,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 6,
        "vis_miles": 3,
        "gust_mph": 17,
        "gust_kph": 27.4,
        "uv": 8,
        "air_quality": {
            "co": 243.7,
            "no2": 2.8,
            "o3": 39,
            "so2": 3.6,
            "pm2_5": 6,
            "pm10": 8.2,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "17:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716377400,
        "time": "2024-05-22 17:00",
        "temp_c": 32,
        "temp_f": 89.5,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 15,
        "wind_kph": 24.1,
        "wind_degree": 151,
        "wind_dir": "SSE",
        "pressure_mb": 1000,
        "pressure_in": 29.54,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 65,
        "cloud": 7,
        "feelslike_c": 38.6,
        "feelslike_f": 101.4,
        "windchill_c": 32,
        "windchill_f": 89.5,
        "heatindex_c": 38.6,
        "heatindex_f": 101.4,
        "dewpoint_c": 24.6,
        "dewpoint_f": 76.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 18.6,
        "gust_kph": 29.9,
        "uv": 8,
        "air_quality": {
            "co": 240.3,
            "no2": 1.6,
            "o3": 35.1,
            "so2": 1.7,
            "pm2_5": 3.1,
            "pm10": 5.2,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "18:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716381000,
        "time": "2024-05-22 18:00",
        "temp_c": 31.1,
        "temp_f": 87.9,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
        },
        "wind_mph": 14.5,
        "wind_kph": 23.4,
        "wind_degree": 144,
        "wind_dir": "SE",
        "pressure_mb": 1001,
        "pressure_in": 29.57,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 70,
        "cloud": 7,
        "feelslike_c": 37.7,
        "feelslike_f": 99.9,
        "windchill_c": 31.1,
        "windchill_f": 87.9,
        "heatindex_c": 37.7,
        "heatindex_f": 99.9,
        "dewpoint_c": 25.1,
        "dewpoint_f": 77.1,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 19.2,
        "gust_kph": 30.9,
        "uv": 8,
        "air_quality": {
            "co": 243.7,
            "no2": 1.4,
            "o3": 26.5,
            "so2": 0.9,
            "pm2_5": 1.7,
            "pm10": 3.8,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "19:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716384600,
        "time": "2024-05-22 19:00",
        "temp_c": 30.8,
        "temp_f": 87.4,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 13,
        "wind_kph": 20.9,
        "wind_degree": 138,
        "wind_dir": "SE",
        "pressure_mb": 1003,
        "pressure_in": 29.61,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 72,
        "cloud": 10,
        "feelslike_c": 37.4,
        "feelslike_f": 99.2,
        "windchill_c": 30.8,
        "windchill_f": 87.4,
        "heatindex_c": 37.4,
        "heatindex_f": 99.2,
        "dewpoint_c": 25.2,
        "dewpoint_f": 77.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 17.2,
        "gust_kph": 27.7,
        "uv": 1,
        "air_quality": {
            "co": 253.7,
            "no2": 1.6,
            "o3": 20.7,
            "so2": 0.9,
            "pm2_5": 1.5,
            "pm10": 3.7,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "20:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716388200,
        "time": "2024-05-22 20:00",
        "temp_c": 30.7,
        "temp_f": 87.2,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 12.8,
        "wind_kph": 20.5,
        "wind_degree": 146,
        "wind_dir": "SSE",
        "pressure_mb": 1003,
        "pressure_in": 29.63,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 72,
        "cloud": 9,
        "feelslike_c": 37.1,
        "feelslike_f": 98.8,
        "windchill_c": 30.7,
        "windchill_f": 87.2,
        "heatindex_c": 37.1,
        "heatindex_f": 98.8,
        "dewpoint_c": 25.1,
        "dewpoint_f": 77.2,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 17.1,
        "gust_kph": 27.5,
        "uv": 1,
        "air_quality": {
            "co": 263.7,
            "no2": 1.8,
            "o3": 18.4,
            "so2": 1.1,
            "pm2_5": 1.5,
            "pm10": 4.1,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "21:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716391800,
        "time": "2024-05-22 21:00",
        "temp_c": 30.6,
        "temp_f": 87,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 9.6,
        "wind_kph": 15.5,
        "wind_degree": 155,
        "wind_dir": "SSE",
        "pressure_mb": 1004,
        "pressure_in": 29.64,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 73,
        "cloud": 8,
        "feelslike_c": 37.1,
        "feelslike_f": 98.7,
        "windchill_c": 30.6,
        "windchill_f": 87,
        "heatindex_c": 37.1,
        "heatindex_f": 98.7,
        "dewpoint_c": 25.2,
        "dewpoint_f": 77.3,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 13,
        "gust_kph": 20.9,
        "uv": 1,
        "air_quality": {
            "co": 287.1,
            "no2": 2.4,
            "o3": 16.5,
            "so2": 1.4,
            "pm2_5": 2.1,
            "pm10": 5.2,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "22:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716395400,
        "time": "2024-05-22 22:00",
        "temp_c": 30.6,
        "temp_f": 87.1,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 6.3,
        "wind_kph": 10.1,
        "wind_degree": 158,
        "wind_dir": "SSE",
        "pressure_mb": 1004,
        "pressure_in": 29.65,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 71,
        "cloud": 11,
        "feelslike_c": 36.7,
        "feelslike_f": 98.1,
        "windchill_c": 30.6,
        "windchill_f": 87.1,
        "heatindex_c": 36.7,
        "heatindex_f": 98.1,
        "dewpoint_c": 24.8,
        "dewpoint_f": 76.6,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 8.5,
        "gust_kph": 13.8,
        "uv": 1,
        "air_quality": {
            "co": 317.1,
            "no2": 3.3,
            "o3": 14.1,
            "so2": 1.6,
            "pm2_5": 2.9,
            "pm10": 7.1,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    },
    {
        "exactTime": "23:00",
        "todayDate": "2024-05-22 ",
        "time_epoch": 1716399000,
        "time": "2024-05-22 23:00",
        "temp_c": 30.4,
        "temp_f": 86.7,
        "is_day": 0,
        "condition": {
            "text": "Clear ",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 7.4,
        "wind_kph": 11.9,
        "wind_degree": 173,
        "wind_dir": "S",
        "pressure_mb": 1003,
        "pressure_in": 29.62,
        "precip_mm": 0,
        "precip_in": 0,
        "snow_cm": 0,
        "humidity": 72,
        "cloud": 15,
        "feelslike_c": 36.5,
        "feelslike_f": 97.7,
        "windchill_c": 30.4,
        "windchill_f": 86.7,
        "heatindex_c": 36.5,
        "heatindex_f": 97.7,
        "dewpoint_c": 24.9,
        "dewpoint_f": 76.7,
        "will_it_rain": 0,
        "chance_of_rain": 0,
        "will_it_snow": 0,
        "chance_of_snow": 0,
        "vis_km": 10,
        "vis_miles": 6,
        "gust_mph": 10.1,
        "gust_kph": 16.2,
        "uv": 1,
        "air_quality": {
            "co": 333.8,
            "no2": 3.9,
            "o3": 12.3,
            "so2": 1.6,
            "pm2_5": 3.5,
            "pm10": 8.1,
            "us-epa-index": 1,
            "gb-defra-index": 1
        }
    }
]);
  const [date, setDate] =useState()
  

  useEffect(() => {
    async function getCurrentReport() {
      try {
        const response = await axios.get(
          `http://api.weatherapi.com/v1/forecast.json?key=4b03e9f34a364637ba424857242005&q=nizampatnam&days=${forcastDays}&aqi=yes&alerts=no`
        );
        setForeCast(response.data.forecast.forecastday);
        setDate(response.data.forecast.forecastday[0].date)
      } catch (err) {
        console.log(err);
      }
    }
    getCurrentReport();
  }, [forcastDays]);
  return (
    <div className="flex max-w-[1100px] mx-auto p-4 gap-3 mb-8">
      <Forecast forecast={forecast} setForecastDays={setForecastDays} setForecastDay={setForecastDay} setDate={setDate}/>
      <SummaryChart date={date} forcastDay={forcastDay} />
    </div>
  );
}
